In [1]:
#Creating Array
distance = [10,5,7,26]
time = [.30,.47,.55,1.20]


In [2]:
#import numpy 
import numpy as np 

In [3]:
#Creating ndArray+++++
np_distance = np.array(distance)
np_time = np.array(time)
speed = np_distance/np_time

In [4]:
speed

array([33.33333333, 10.63829787, 12.72727273, 21.66666667])

In [5]:
#Creating and Printing ndarrays
first_numpy_array=np.array([1,2,3,4])

In [6]:
print(first_numpy_array)

[1 2 3 4]


In [7]:
#Array with Zeros
array_with_zeros=np.zeros((3,3))

In [8]:
array_with_zeros

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [9]:
#Array with Ones
array_with_ones=np.ones((3,3))

In [10]:
array_with_ones

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [17]:
#Array with empty
array_with_empty=np.empty((2,3))

In [18]:
array_with_empty

array([[0., 0., 0.],
       [0., 0., 0.]])

In [26]:
#Array with Arrange method
np_arange=np.arange(12)

In [27]:
print(np_arange)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [28]:
#Reshape method to create/change array
np_arange.reshape(3,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [30]:
#Linspace for linerly (equal) spaced data elements
np_linspce=np.linspace(1,6,5)

In [31]:
print(np_linspce)

[1.   2.25 3.5  4.75 6.  ]


In [32]:
#one dimensional array
One_d_array=np.arange((15))

In [33]:
print(One_d_array)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [35]:
#two dimensional array
Two_d_array=One_d_array.reshape(3,5)

In [36]:
print(Two_d_array)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [37]:
#Three dimensional array
Three_d_array=np.arange(27).reshape(3,3,3)

In [38]:
print(Three_d_array)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


In [43]:
#Class and Attributes of ndArray
# 1.ndarray.ndim
np_lang=np.array(['English','Hindi','Marathi','Bengali','Tamil','Kannada'])
np_region_of_lang=np.array(['England','North','Maharashtra','West Bengal','Tamilnadu','Karnataka'])

In [44]:
np_lang.ndim

1

In [46]:
np_region_of_lang.ndim

1

In [47]:
# 2.ndarray.shape
np_lang.shape

(6,)

In [48]:
np_region_of_lang.shape

(6,)

In [49]:
# 3.ndarray.size
np_lang.size

6

In [50]:
np_region_of_lang.size

6

In [51]:
# 4. ndarray.dtype
np_lang.dtype

dtype('<U7')

In [52]:
np_region_of_lang.dtype

dtype('<U11')

In [53]:
#numpy basic operations
first_count=[6,7,8,9,]
second_count=[10,11,12,13]


In [55]:
np_first_count=np.array(first_count)
np_second_count=np.array(second_count)
np_first_count+np_second_count  #vector addition

array([16, 18, 20, 22])

In [56]:
#Mathmatical Operations
np.add(30,45)

75

In [57]:
np.subtract(85,20)

65

In [58]:
#ndarray multiplications
nd_daily_wage=np.array([2,4,6,8])*2

In [59]:
print(nd_daily_wage)

[ 4  8 12 16]


In [61]:
sum(nd_daily_wage)

40

In [28]:
#Comparision Operations
np_hours=np.array([2,4,6,8])

In [29]:
np_hours[np_hours>2]

array([4, 6, 8])

In [30]:
np_hours[np_hours!=6]

array([2, 4, 8])

In [31]:
#Logical Operations
np.logical_and(np_hours>2,np_hours<10)

array([False,  True,  True,  True])

In [76]:
np.logical_not(np_hours>7)

array([ True,  True,  True, False])

In [23]:
import numpy as np

In [24]:
#Comparison Operations
np_count=np.array([10,20,30,40,50])

In [25]:
#check if element is more than 10
np_count[np_count>10]

array([20, 30, 40, 50])

In [27]:
#check if count not equals to 40
np_count[np_count!=50]

array([10, 20, 30, 40])

In [32]:
#Logical And Operation
np.logical_and(np_count>10,np_count<50)

array([False,  True,  True,  True, False])

In [34]:
#Logical NOT operations
np.logical_not(np_count>20)

array([ True,  True, False, False, False])

In [36]:
#Accessing Array Elements : Indexing
Working_Shifts=np.array([[6,3,8,5],[12,9,2,11]])  # Creating 2D Array

In [39]:
first_shift=Working_Shifts[0]
first_shift

array([6, 3, 8, 5])

In [40]:
second_shift=Working_Shifts[1]
second_shift

array([12,  9,  2, 11])

In [44]:
first_shift_start=Working_Shifts[0][0]

In [45]:
first_shift_start

6

In [48]:
first_shift_time=Working_Shifts[:,0]

In [49]:
first_shift_time

array([ 6, 12])

In [50]:
#Slicing
Working_Shifts.shape

(2, 4)

In [56]:
shifts_data=Working_Shifts[:,1:4]

In [57]:
shifts_data

array([[ 3,  8,  5],
       [ 9,  2, 11]])

In [59]:
#Iteration
for i in Working_Shifts:
    print(i)

[6 3 8 5]
[12  9  2 11]


In [63]:
#Indexing with Boolean Arrays
test_score=np.array([[40,45,80,95],[75,60,35,86]])

In [64]:
passing_score=test_score>35

In [65]:
passing_score

array([[ True,  True,  True,  True],
       [ True,  True, False,  True]])

In [66]:
test_score[passing_score] #send passing score as an argument to test scores bject

array([40, 45, 80, 95, 75, 60, 86])

In [67]:
#Mathmatical Functions of Numpy


In [70]:
#Universal Fnction / ufunc example
#Square root
np_sqrt=np.sqrt([4,9,16,64])


In [71]:
np_sqrt

array([2., 3., 4., 8.])

In [72]:
from numpy import pi

In [77]:
#Trigonometric functions
np.cos(0) 

1.0

In [74]:
np.sin(pi/2)

1.0

In [76]:
np.cos(pi)

-1.0

In [78]:
#Floor Function
np.floor([1.5,1.6,2.6,2.5,-1.4])

array([ 1.,  1.,  2.,  2., -2.])

In [80]:
#Exp Function
np.exp([2,6,1])

array([  7.3890561 , 403.42879349,   2.71828183])

In [89]:
#Shape Manipulation
#Flatterns the dataset
data_set=np.array([[10,15,20,25,30,50],[35,40,45,85,90,65]])
data_set.ravel()

array([10, 15, 20, 25, 30, 50, 35, 40, 45, 85, 90, 65])

In [91]:
#changing dataset / reshaping o 3rows and 4 col
data_set.reshape(3,4)

array([[10, 15, 20, 25],
       [30, 50, 35, 40],
       [45, 85, 90, 65]])

In [92]:
#resize again to 2 rows and 6 col
data_set.resize(2,6)

In [93]:
data_set

array([[10, 15, 20, 25, 30, 50],
       [35, 40, 45, 85, 90, 65]])

In [94]:
#Split array into two
np.hsplit(data_set,2)

[array([[10, 15, 20],
        [35, 40, 45]]),
 array([[25, 30, 50],
        [85, 90, 65]])]

In [100]:
new_dataset_1=np.array([10,12,14,16,18,20])

In [101]:
new_dataset_2=np.array([9,12,15,18,21,24])

In [102]:
#stacks the array together
np.hstack((new_dataset_1,new_dataset_2))

array([10, 12, 14, 16, 18, 20,  9, 12, 15, 18, 21, 24])

In [103]:
#broadcasting
array_a=np.array([2,4,6,8])

In [104]:
array_b=np.array([10,12,14,16])

In [105]:
#multiply arrays
array_a*array_b

array([ 20,  48,  84, 128])

In [106]:
scalar_c=.3

In [107]:
array_a*scalar_c

array([0.6, 1.2, 1.8, 2.4])

In [108]:
#Linear Algebra - Transpose
test_score.transpose()

array([[40, 75],
       [45, 60],
       [80, 35],
       [95, 86]])

In [112]:
#Linear Algebra | inverse and trace functions
#inverse
test_array=np.array([[10,20],[15,20]])

In [113]:
np.linalg.inv(test_array)

array([[-0.2 ,  0.2 ],
       [ 0.15, -0.1 ]])

In [114]:
#trace
np.trace(test_array) #sum of diagonal elements sum of higher data elements

30